server:
  port: 2001
spring:
  application:
    name: seata-order
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.219.202:8848
        username: nacos
        password: nacos
        group: SEATA_GROUP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.219.202:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 15090667928Hh_
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath*:mapper/*.xml

seata:
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      group: ${spring.cloud.nacos.discovery.group}
feign:
  httpclient:
    connection-timeout: 60000
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  OkToRetryOnAllOperations: false
  ServerListRefreshInterval: 6000
  MaxAutoRetriesNextServer: 3
