server:
  port: 2001
spring:
  application:
    name: seata-order
  cloud:
    nacos:
      discovery:
        server-addr: xxx:8848
        username: nacos
        password: nacos
        group: SEATA_GROUP
#        namespace: 6c990727-93b2-4081-a8c6-6b015c56eda2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xxx
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath*:mapper/*.xml

seata:
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      group: ${spring.cloud.nacos.discovery.group}
#      namespace: 6c990727-93b2-4081-a8c6-6b015c56eda2
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      group: ${spring.cloud.nacos.discovery.group}
      namespace: 51915a62-d2d6-43d4-8f45-86b159eb90f5
  service:
    vgroup-mapping:
      my_test_tx_group: default

feign:
  httpclient:
    connection-timeout: 20000
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

#ribbon:
#  ConnectTimeout: 100000
#  ReadTimeout: 100000
#  MaxAutoRetries: 0
#  OkToRetryOnAllOperations: false
#  ServerListRefreshInterval: 6000
#  MaxAutoRetriesNextServer: 3

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
